### ISSUE TITLE
Data pre-process

### ISSUE THREAD

**Issue by VinhDatHa** [KingLeo2000/vietnamese-spell-correct-and-text-classify#7]
Em chào anh, em có thấy được project của anh và mong muốn được kế thừa phần Spell-correct của anh để có thể tích hợp và phát triển vào đồ án môn học của em hiện tại. Tuy nhiên, trong quá trình nghiên cứu em gặp khó khăn khi repo bị thiếu mất file "VNTC_data.pkl" nên không thể tiếp tục được ạ. Rất hy vọng anh có thể cho em xin file "VNTC_data.pkl" để có thể tiếp tục phát triển dự án ạ. Em xin chân thành cám ơn ạ

**Comment by VietHoang1512** [comment]
Hi em, ừ, em đang chạy code bị lỗi, và nó báo thiếu file đó à em?

Vào Th 7, 22 thg 1, 2022 lúc 23:18 Vinh Dat Ha ***@***.***>
đã viết:

**Comment by VietHoang1512** [comment]
Hiện giờ thì anh cũng không rõ là có file VNTC_data.pkl ở đâu, nhưng theo
anh hiểu là em đang cần dữ liệu VNTC (https://github.com/duyvuleo/VNTC)
được dump dưới dạng .pkl. Em có thể tham khảo cách làm tương tự ở đây:
https://drive.google.com/drive/folders/1pJlmeg442ZwapSPXwwCu6EAo7aN1vHxT?usp=sharing
file merge_data.ipynb

Vào Th 7, 22 thg 1, 2022 vào lúc 23:19 Hoang Phan <
***@***.***> đã viết:

**Comment by VinhDatHa** [comment]
Vâng, em cám ơn anh rất nhiều vì đã giúp đỡ ạ. Chúc anh năm mới mạnh khỏe và gặp nhiều may mắn ạ. Em cám ơn
